# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    rsavinkov\Weather\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,DTO,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    rsavinkov\Weather\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    rsavinkov\Weather\Service\ScaleConverter\ScaleConverter:
        class: 'rsavinkov\Weather\Service\ScaleConverter\ScaleConverter'
        arguments:
            - '@rsavinkov\Weather\Service\ScaleConverter\CelsiusConverter'
            - '@rsavinkov\Weather\Service\ScaleConverter\FahrenheitConverter'

    rsavinkov\Weather\Service\PredictionDataParser\PredictionDataParser:
        class: 'rsavinkov\Weather\Service\PredictionDataParser\PredictionDataParser'
        arguments:
            - '@rsavinkov\Weather\Service\PredictionDataParser\CsvPredictionDataParser'
            - '@rsavinkov\Weather\Service\PredictionDataParser\JsonPredictionDataParser'
            - '@rsavinkov\Weather\Service\PredictionDataParser\XmlPredictionDataParser'

    rsavinkov\Weather\Service\PredictionsActualizer:
        class: 'rsavinkov\Weather\Service\PredictionsActualizer'
        arguments:
            - '@rsavinkov\Weather\Repository\WeatherPredictionRepository'
            - '@rsavinkov\Weather\Service\PredictionDataParser\PredictionDataParser'
            - '@rsavinkov\Weather\Integration\Prediction\Dummy\CsvPredictionProvider'
            - '@rsavinkov\Weather\Integration\Prediction\Dummy\JsonPredictionProvider'
            - '@rsavinkov\Weather\Integration\Prediction\Dummy\XmlPredictionProvider'
